### ISSUE TITLE
[Minor/Player] 'Spar' Giving Switched Echo Responses

### ISSUE THREAD

**Issue by Sorenthaz** [volundmush/dbat#21]
So when you're in spar stance and type spar to exit it, it says you enter it and vice versa.

![image](https://github.com/volundmush/dbat/assets/156051882/368dc61a-50d4-4108-b5e8-d617e5190c84)

**Comment by PetalFoxx** [comment]
Fixed in https://github.com/volundmush/dbat/pull/24
