### ISSUE TITLE
[Minor/Immortal] Medit Level Field Showing 0 At All Times

### ISSUE THREAD

**Issue by Sorenthaz** [volundmush/dbat#22]
When going in to edit mobs it shows their level is 0 no matter what value you try to assign to it.  However, this is purely cosmetic and the level changes do get registered and appear when checking a mob's vstat/stat file.  

![image](https://github.com/volundmush/dbat/assets/156051882/56ff9d4f-564d-42c0-955b-814fb938b44a)

**Comment by PetalFoxx** [comment]
Fixed in https://github.com/volundmush/dbat/pull/24
