### ISSUE TITLE
[Medium/Immortal] Mobs Unable to Be Assigned Classes (Sensei) in Medit; Stays Commoner

### ISSUE THREAD

**Issue by Sorenthaz** [volundmush/dbat#23]
This is an issue that has been occurring at the very least since I started learning how to use mob edit over a year ago.  Mobs are stuck on Commoner for their Class, making one unable to create new mobs or edit existing mobs that use the skillsets outside of the Commoner class.  So all I can do is make mobs that have the Commoner class, and editing existing mobs defaults them to Commoner if attempting to edit their class.

**Comment by PetalFoxx** [comment]
Fixed in https://github.com/volundmush/dbat/pull/24
