### ISSUE TITLE
[Minor/Immortal] SNET history ('history snet') is not saved for immortals

### ISSUE THREAD

**Issue by Sorenthaz** [volundmush/dbat#30]
As title says, immortals seem unable to pull up the history of snet messages.  Regular mortal players are able to without issue.

![image](https://github.com/volundmush/dbat/assets/156051882/f3635ff7-f8d0-422b-b1f2-ca1cefa30b7f)

**Comment by PetalFoxx** [comment]
Is it only snet history having the issue, and does it show up when looking at the history of all channels?

**Comment by Sorenthaz** [comment]
No it happens on hist all as well.

**Comment by Sorenthaz** [comment]
Essentially it only saves history of what the immortal personally says, not what other users say.

![image](https://github.com/volundmush/dbat/assets/156051882/a605d617-376f-4009-b6a9-8db9bb50d690)

**Comment by PetalFoxx** [comment]
In theory this is fixed with the latest patch, I couldn't test it solo. The entries in History might show up twice, however.

**Comment by Sorenthaz** [comment]
Yep looks like it should be good to go now!
![image](https://github.com/volundmush/dbat/assets/156051882/981c04a1-2b29-484d-ae52-0788535ebaad)
